name: Base Image Build
on:
  push:
    paths:
      - 'Dockerfile.base'
    branches:
      - master
  schedule:
    - cron: '0 0 * * 0'  # Weekly rebuild
  workflow_dispatch:

jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Free disk space
        run: |
          echo "Initial disk space:"
          df -h
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          sudo apt-get clean
          docker system prune -af
          echo "Disk space after cleanup:"
          df -h

      - name: Set date environment variable
        run: echo "date=$(date '+%Y-%m-%d-%H%M')" >> $GITHUB_ENV

      - name: Docker Build Base Image
        run: |
          export DOCKER_TLS_CERTDIR=""
          docker build -f Dockerfile.base . -t ${{ vars.DOCKER_PRIVATE }}/genai/remote-client-server-base:$date
          docker tag ${{ vars.DOCKER_PRIVATE }}/genai/remote-client-server-base:$date ${{ vars.DOCKER_PRIVATE }}/genai/remote-client-server-base:latest
      
      - name: Docker login for DOCKER_SEMOSS
        run: |
          echo ${{ secrets.SEMOSS_DOCKER_PASS}} | docker login ${{ vars.DOCKER_SEMOSS }} -u ${{ secrets.SEMOSS_DOCKER_USER}} --password-stdin
          docker tag ${{ vars.DOCKER_PRIVATE }}/genai/remote-client-server-base:$date ${{ vars.DOCKER_SEMOSS }}/genai/remote-client-server-base:$date
          docker tag ${{ vars.DOCKER_PRIVATE }}/genai/remote-client-server-base:$date ${{ vars.DOCKER_SEMOSS }}/genai/remote-client-server-base:latest
          docker push ${{ vars.DOCKER_SEMOSS }}/genai/remote-client-server-base:$date
          docker push ${{ vars.DOCKER_SEMOSS }}/genai/remote-client-server-base:latest
      
      - name: Docker logout for DOCKER_SEMOSS
        run: docker logout ${{ vars.DOCKER_SEMOSS }}

      - name: Docker login for DOCKER_PRIVATE
        run: |
          echo ${{ secrets.DOCKER_PASS}} | docker login ${{ vars.DOCKER_PRIVATE }} -u ${{ secrets.DOCKER_USER}} --password-stdin
          docker push ${{ vars.DOCKER_PRIVATE }}/genai/remote-client-server-base:$date
          docker push ${{ vars.DOCKER_PRIVATE }}/genai/remote-client-server-base:latest
      
      - name: Docker logout for DOCKER_PRIVATE
        run: docker logout ${{ vars.DOCKER_PRIVATE }}