name: Docker Build
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Free disk space
        run: |
          # Show initial disk space
          echo "Initial disk space:"
          df -h
          
          # Remove unnecessary large packages and caches
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          sudo apt-get clean
          docker system prune -af
          
          # Show disk space after cleanup
          echo "Disk space after cleanup:"
          df -h

      - name: Set date environment variable
        run: echo "date=$(date '+%Y-%m-%d')" >> $GITHUB_ENV

      - name: Docker Build
        run: |
          export DOCKER_TLS_CERTDIR=""
          ls -lah
          pwd
          echo ${{ secrets.DOCKER_PASS}} | docker login ${{ vars.DOCKER_PRIVATE }} -u ${{ secrets.DOCKER_USER}} --password-stdin
          echo ${{ secrets.SEMOSS_DOCKER_PASS}} | docker login ${{ vars.DOCKER_SEMOSS }} -u ${{ secrets.SEMOSS_DOCKER_USER}} --password-stdin
          docker build . -t ${{ vars.DOCKER_PRIVATE }}/genai/remote-client-server:$date
          docker tag ${{ vars.DOCKER_PRIVATE }}/genai/remote-client-server:$date ${{ vars.DOCKER_SEMOSS }}/genai/remote-client-server:$date
          docker push ${{ vars.DOCKER_SEMOSS }}/genai/remote-client-server:$date
          docker push  ${{ vars.DOCKER_PRIVATE }}/genai/remote-client-server:$date